search:
    Training\Bundle\UserNamingBundle\Entity\UserNamingType:
        alias: user_naming_type
        route:
            name: training_user_naming_type_view
            parameters:
                id: id

        search_template: '@TrainingUserNaming/UserNamingType/search-result.html.twig'
        fields:
            -   name: title
                target_type: text
                target_fields: [ title ]